# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Jahns - UX/UI Nashville, TN
email: imdavidjahns@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm David Jahns. I am a UX Designer and UI Developer currently residing 
  in Nashville, TN. I have too many ideas for my own good.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidhasideas.com" # the base hostname & protocol for your site
twitter_username: davidjahns
github_username:  davidjahns

# Build settings
markdown: kramdown
source: source 
desination: _site
